### ISSUE TITLE
Umm... `alias cp=`?

### ISSUE THREAD

**Issue by MrMino** [MenkeTechnologies/zsh-cargo-completion#1]
I would find this very helpful, if it wasn't for the `cp="cargo package"` alias which shadows the `cp` command. Is the usage of `cargo package` really this frequent enough to motivate alias?

I'm potentially missing something very obvious here, please excuse me if that's the case :grinning:.

**Comment by MrMino** [comment]
Actually, I think this is only a typo in your README.md...

**Comment by MenkeTechnologies** [comment]
merged
